# Generated by Django 2.2.2 on 2021-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='PRICEID',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='', verbose_name='ΤΙΜΗ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='TIMEID',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='', verbose_name='ΩΡΑ'),
        ),
    ]
