# Generated by Django 2.2.2 on 2021-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ΠΕΡΙΓΡΑΦΗ ΤΑΙΝΙΑΣ'),
        ),
    ]
