# Generated by Django 2.2.2 on 2021-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210428_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'Ταινία', 'verbose_name_plural': 'Ταινίες'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ACTOR',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='CATEGORYID',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='DIRECTOR',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='OWNER',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='TITLE',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='COVERURL',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='DATE',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='DESCRIPTION',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='IMBDURL',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='PRICEID',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='TIMEID',
        ),
        migrations.AddField(
            model_name='movie',
            name='coverUrl',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='ΕΞΩΦΥΛΟ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(null=True, verbose_name='ΗΜΕΡΟΜΗΝΙΑ ΠΡΟΒΟΛΗΣ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ΠΕΡΙΓΡΑΦΗ ΤΑΙΝΙΑΣ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imbdUrl',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='movie',
            name='priceId',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='', verbose_name='ΤΙΜΗ ΕΙΣΗΤΗΡΙΟΥ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='timeId',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default='', verbose_name='ΩΡΑ ΠΡΟΒΟΛΗΣ'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
