# Generated by Django 2.2.2 on 2021-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='TRAILER ΤΑΙΝΙΑΣ'),
        ),
    ]
