# Generated by Django 2.2.2 on 2021-05-06 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210505_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Περιγραφή κατηγορίας')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Κατηγορία',
                'verbose_name_plural': 'Κατηγορίες',
                'db_table': 'category',
                'ordering': ['desc'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Περιγραφή Τιμής Εισητηρίου')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Τιμή Εισητηρίου',
                'verbose_name_plural': 'Τιμές εισητηρίων',
                'db_table': 'price',
                'ordering': ['desc'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Περιγραφή Ώρας Προβολής')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ώρα Προβολής',
                'verbose_name_plural': 'Ώρες Προβολής',
                'db_table': 'time',
                'ordering': ['desc'],
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='priceId',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='timeId',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='ΗΜΕΡΟΜΗΝΙΑ ΠΡΟΒΟΛΗΣ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(db_table='movie_category', related_name='movies', to='movies.Category', verbose_name='Κατηγορία Ταινίας'),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.ManyToManyField(db_table='movie_price', related_name='movies', to='movies.Price', verbose_name='Τιμή Εισητηρίου'),
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.ManyToManyField(db_table='movie_time', related_name='movies', to='movies.Time', verbose_name='Ώρα Προβολής'),
        ),
    ]
