# Generated by Django 2.2.2 on 2021-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210507_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='priceId',
            field=models.IntegerField(choices=[(0, 'Όλα'), (1, 'Φοιτητικό/Στρατιωτικό: 5,5€'), (2, 'Παιδικό:7,5€'), (3, 'Αίθουσα 2D:10€'), (4, 'Αίθουσα 3D:11€'), (5, 'Αίθουσα DOLBY:11€'), (6, 'Αίθουσα DOLBY-3D:12€'), (7, 'Αίθουσα GOLD:20€')], default='', verbose_name='ΤΙΜΗ ΕΙΣΗΤΗΡΙΟΥ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='timeId',
            field=models.IntegerField(choices=[(0, '(Όλα)'), (1, '18:00 μμ'), (2, '19:00 μμ'), (3, '20:00 μμ'), (4, '21:00 μμ'), (5, '22:00 μμ'), (6, '23:00 μμ'), (7, '24:00 μμ')], default='', verbose_name='ΩΡΑ ΠΡΟΒΟΛΗΣ'),
        ),
    ]
