# Generated by Django 2.2.2 on 2021-05-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210507_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='viewdate',
            new_name='viewDate',
        ),
    ]
