# Generated by Django 3.2.2 on 2021-05-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210506_1200'),
        ('movies', '0006_auto_20210507_1040'),
    ]

    operations = [
    ]
